parameters:
    locale: 'en'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Console\ClassContextElementFactory:
        decorates: MsgPhp\Domain\Infra\Console\Context\ClassContextElementFactoryInterface
        arguments:
            '$factory': '@App\Console\ClassContextElementFactory.inner'
    App\Controller\:
        resource: '../src/Controller'
        tags: [controller.service_arguments]
    App\Security\JwtTokenErrorHandler:
        tags:
            - { name: kernel.event_listener, event: !php/const Lexik\Bundle\JWTAuthenticationBundle\Events::JWT_NOT_FOUND, method: handle }
            - { name: kernel.event_listener, event: !php/const Lexik\Bundle\JWTAuthenticationBundle\Events::JWT_INVALID, method: handle }
    App\Security\OauthUserProvider: ~
    App\Security\PasswordConfirmation:
        arguments:
            '$secret': '%kernel.secret%'
    App\Security\UserChecker: ~
    App\Security\UserRolesProvider: ~
    MsgPhp\User\Infra\Security\UserRolesProviderInterface: '@App\Security\UserRolesProvider'
