parameters:
    locale: 'en'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # App
    App\Console\ClassContextElementFactory:
        decorates: MsgPhp\Domain\Infra\Console\Context\ClassContextElementFactoryInterface
        arguments:
            '$factory': '@App\Console\ClassContextElementFactory.inner'
    App\Controller\:
        resource: '../src/Controller'
        tags: [controller.service_arguments]

    # API
    App\Api\Endpoint\:
        resource: '../src/Api/Endpoint'
        tags: [controller.service_arguments]
    App\Api\Projection\DocumentTransformer\:
        resource: '../src/Api/Projection/DocumentTransformer'

    # Security
    App\Security\JwtTokenSubscriber: ~
    App\Security\OauthUserProvider: ~
    App\Security\PasswordConfirmation:
        arguments:
            '$secret': '%kernel.secret%'
    App\Security\UserChecker: ~
    App\Security\UserRolesProvider: ~
    MsgPhp\User\Infra\Security\UserRolesProviderInterface: '@App\Security\UserRolesProvider'
